### ISSUE TITLE
Building the repo

### ISSUE THREAD

**Issue by abdabdul** [Al-khwarizmi-780/OpenKF#3]
Dear Mohanad,
thank you for making this repo available.
As a part of a bigger project, I was trying to build this repo on my Ubuntu 20.04 machine using the same steps in the `bootstrap-openkf.bat`, but tweaked a little bit to work with the Linux terminal:
`mkdir -p cpp/build && cd cpp/build`
`cmake -S ./cpp -B ./cpp/build`
`cmake --build ./cpp/build`
The build command throws the following error:
`/home/abdul/Kalman_Filter/OpenKF/cpp/Examples/ekf_range_sensor/../../kalman_filter/unscented_transform.h:100:51: error: ‘_weights’ was not declared in this scope; did you mean ‘weights’?
  100 |         Matrix<1, SIGMA_DIM> & weights() { return _weights; }`
  
![image](https://github.com/Al-khwarizmi-780/OpenKF/assets/110027360/b6a523c3-196d-471f-8474-6823eacb7617)

Any idea how to solve this problem?

**Comment by abdabdul** [comment]
If I naively change `_weights` to `weights`, I get another error:
`In file included from /home/abdul/Kalman_Filter/OpenKF/cpp/Examples/ukf_range_sensor/main.cpp:16:
/home/abdul/Kalman_Filter/OpenKF/cpp/Examples/ukf_range_sensor/../../kalman_filter/unscented_kalman_filter.h:275:18: error: declaration of template parameter ‘DIM_X’ shadows template parameter
  275 |         template<size_t DIM_X>`
  
  
![image](https://github.com/Al-khwarizmi-780/OpenKF/assets/110027360/cae3f580-eff7-4d90-8d02-7b81c2962e7f)

**Comment by Al-khwarizmi-780** [comment]
Hello [abdabdul](https://github.com/abdabdul)

Can you please try this PR locally and see if the build works?
https://github.com/Al-khwarizmi-780/OpenKF/pull/4

**Comment by abdabdul** [comment]
Thank you for your quick response!
Yes, the build works from the branch! you just need to correct some typos as following:
in `cpp/CMakeLists.txt` change `add_subdirectory(examples)` to `add_subdirectory(Examples)`
in `cpp/Examples/CMakeLists.txt` remove `add_subdirectory(gnss_application)`
in `cpp/openkf/CMakeLists.txt` remove `helpers/helpers.h` `gnss/representation.h` `gnss/geodetic.h`

**Comment by Al-khwarizmi-780** [comment]
I updated the PR, you can try now.

**Comment by abdabdul** [comment]
All fine, thank you!  :+1:
